from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from PIL import Image


PROJECT_ROOT = Path(__file__).resolve().parents[1]
ARTIFACT_ROOT = PROJECT_ROOT / "artifacts" / "island-territory-v2"
CONTRACT_ROOT = PROJECT_ROOT / "contracts"
OUTPUT_PATH = (
    PROJECT_ROOT
    / "mod0"
    / "ue4ss"
    / "PalFactionTerritory0"
    / "Scripts"
    / "pwft"
    / "pal_faction_island_mask.lua"
)

PAL_ISLANDS = (
    ("pwft.island.central_southeast_archipelago", 1, 0),
    ("pwft.island.desert", 1, 2),
    ("pwft.island.snow", 1, 3),
    ("pwft.island.volcano", 2, 1),
    ("pwft.island.feybreak", 2, 2),
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def lua_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the checked-in Lua mask differs from the generated result",
    )
    args = parser.parse_args()

    manifest = json.loads(
        (ARTIFACT_ROOT / "island_geometry_manifest.v2.json").read_text(encoding="utf-8")
    )
    fast_travel = json.loads(
        (CONTRACT_ROOT / "fast_travel_territories.v1.json").read_text(encoding="utf-8")
    )
    projection = fast_travel["classificationPolicy"]["projection"]
    threshold = int(manifest["geometry"]["selectorThreshold"])

    pack_paths = {
        1: ARTIFACT_ROOT / "T_PFT_IslandGeometryPack_01.png",
        2: ARTIFACT_ROOT / "T_PFT_IslandGeometryPack_02.png",
    }
    expected_hashes = {
        int(item["file"].split("_")[-1].split(".")[0]): item["sha256"]
        for item in manifest["packs"][:2]
    }
    for pack_index, pack_path in pack_paths.items():
        actual = sha256(pack_path)
        if actual != expected_hashes[pack_index]:
            raise RuntimeError(
                f"geometry pack hash mismatch: {pack_path.name} {actual}"
            )

    images = {
        pack_index: Image.open(pack_path).convert("RGBA")
        for pack_index, pack_path in pack_paths.items()
    }
    texture_size = int(projection["textureSize"])
    if any(image.size != (texture_size, texture_size) for image in images.values()):
        raise RuntimeError("geometry packs must match the projection texture size")

    rows: list[list[tuple[int, int, int]]] = [[] for _ in range(texture_size)]
    pixel_counts = [0 for _ in PAL_ISLANDS]
    sample_pixels: list[tuple[int, int] | None] = [None for _ in PAL_ISLANDS]

    for y in range(texture_size):
        classified: list[int] = [0] * texture_size
        for island_index, (_, pack_index, channel_index) in enumerate(PAL_ISLANDS, start=1):
            channel = images[pack_index].getchannel(channel_index)
            for x in range(texture_size):
                if channel.getpixel((x, y)) > threshold:
                    if classified[x] != 0:
                        raise RuntimeError(
                            f"overlapping Pal island masks at pixel ({x},{y})"
                        )
                    classified[x] = island_index
                    pixel_counts[island_index - 1] += 1
                    if sample_pixels[island_index - 1] is None:
                        sample_pixels[island_index - 1] = (x, y)

        x = 0
        while x < texture_size:
            island_index = classified[x]
            if island_index == 0:
                x += 1
                continue
            start = x
            while x + 1 < texture_size and classified[x + 1] == island_index:
                x += 1
            rows[y].append((start, x, island_index))
            x += 1

    expected_pixels = manifest["geometry"]["islandPixels"]
    for island_index, (island_id, _, _) in enumerate(PAL_ISLANDS):
        if pixel_counts[island_index] != int(expected_pixels[island_id]):
            raise RuntimeError(
                f"pixel count mismatch for {island_id}: "
                f"{pixel_counts[island_index]} != {expected_pixels[island_id]}"
            )

    lines = [
        "-- Generated by tools/generate_pal_faction_mask.py.",
        "-- This is the exact approved whole-island geometry used by the faction map.",
        "-- Coordinates are zero-based T_WorldMap pixels after the pinned world projection.",
        "local Mask = {}",
        "",
        "Mask.schemaVersion = \"1.0.0\"",
        f"Mask.textureSize = {texture_size}",
        "Mask.projection = {",
        f"    minX = {projection['minX']},",
        f"    minY = {projection['minY']},",
        f"    maxX = {projection['maxX']},",
        f"    maxY = {projection['maxY']},",
        "}",
        "Mask.islands = {",
    ]
    for island_index, (island_id, _, _) in enumerate(PAL_ISLANDS, start=1):
        sample_x, sample_y = sample_pixels[island_index - 1] or (-1, -1)
        lines.append(
            "    { id = %s, pixelCount = %d, sampleX = %d, sampleY = %d },"
            % (
                lua_quote(island_id),
                pixel_counts[island_index - 1],
                sample_x,
                sample_y,
            )
        )
    lines.extend(
        [
            "}",
            "",
            "-- Each row stores flat triples: startX, endX, islandIndex.",
            "Mask.rows = {",
        ]
    )
    for y, row in enumerate(rows):
        if not row:
            continue
        flat = ", ".join(str(value) for run in row for value in run)
        lines.append(f"    [{y + 1}] = {{ {flat} }},")
    lines.extend(
        [
            "}",
            "",
            "function Mask.classify_pixel(pixel_x, pixel_y)",
            "    local x = math.floor(tonumber(pixel_x) or -1)",
            "    local y = math.floor(tonumber(pixel_y) or -1)",
            "    if x < 0 or y < 0 or x >= Mask.textureSize or y >= Mask.textureSize then",
            "        return nil",
            "    end",
            "    local row = Mask.rows[y + 1]",
            "    if row == nil then",
            "        return nil",
            "    end",
            "    for offset = 1, #row, 3 do",
            "        if x >= row[offset] and x <= row[offset + 1] then",
            "            local island = Mask.islands[row[offset + 2]]",
            "            return island and island.id or nil",
            "        end",
            "    end",
            "    return nil",
            "end",
            "",
            "function Mask.world_to_pixel(world_x, world_y)",
            "    local x = tonumber(world_x)",
            "    local y = tonumber(world_y)",
            "    if x == nil or y == nil then",
            "        return nil, nil",
            "    end",
            "    local projection = Mask.projection",
            "    local pixel_x = math.floor(",
            "        ((y - projection.minY) / (projection.maxY - projection.minY))",
            "            * Mask.textureSize",
            "    )",
            "    local pixel_y = math.floor(",
            "        (1.0 - ((x - projection.minX) / (projection.maxX - projection.minX)))",
            "            * Mask.textureSize",
            "    )",
            "    return pixel_x, pixel_y",
            "end",
            "",
            "function Mask.classify_world(world_x, world_y)",
            "    local pixel_x, pixel_y = Mask.world_to_pixel(world_x, world_y)",
            "    if pixel_x == nil then",
            "        return nil",
            "    end",
            "    return Mask.classify_pixel(pixel_x, pixel_y)",
            "end",
            "",
            "return Mask",
            "",
        ]
    )

    generated = "\n".join(lines)
    if args.check:
        if not OUTPUT_PATH.exists():
            raise RuntimeError(f"generated mask is missing: {OUTPUT_PATH}")
        current = OUTPUT_PATH.read_text(encoding="utf-8")
        if current != generated:
            raise RuntimeError(
                "generated Pal-faction mask is stale; run "
                "python tools/generate_pal_faction_mask.py"
            )
    else:
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_PATH.write_text(generated, encoding="utf-8", newline="\n")
    print(
        f"PASS {'checked' if args.check else 'generated'} "
        f"{OUTPUT_PATH.relative_to(PROJECT_ROOT)} "
        f"with {sum(pixel_counts)} Pal-faction pixels"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
